#!/bin/bash
export CUDA_VISIBLE_DEVICES=0
python train.py \
  --config-file configs/prompt/cub.yaml \
  MODEL.TYPE vit \
  DATA.BATCH_SIZE 128 \
  MODEL.PROMPT.INITIATION mpa \
  MODEL.PROMPT.KOOPMAN_ENABLED True \
  MODEL.PROMPT.KOOPMAN_DIM 256 \
  MODEL.PROMPT.KOOPMAN_WEIGHT 0.5 \
  MODEL.PROMPT.LYAPUNOV_WEIGHT 0.2 \
  MODEL.PROMPT.KOOPMAN_MOD global \
  MODEL.PROMPT.DEEP True \
  MODEL.PROMPT.DROPOUT 0.1 \
  DATA.FEATURE sup_vitb16_imagenet21k \
  DATA.NAME CUB \
  DATA.NUMBER_CLASSES 200 \
  SOLVER.BASE_LR 0.25 \
  SOLVER.WEIGHT_DECAY 0.001 \
  SEED 42 \
  MODEL.MODEL_ROOT /path/to/data \
  DATA.DATAPATH /path/to/data/CUB_200_2011 \
  OUTPUT_DIR output
